docs: 設計概要
approvers/radwimpiece pull request #5
Opened 2023-05-16 00:32 UTC by Nanai10a

close #

### Type of Change:

- `docs/ARCHITECTURE.md` に簡単な設計の概略
- `docs/schema.ts` に必要なインタフェースの定義 (そのまま使える)

### Details of implementation (実施内容)

書いた.

### Additional Information (追加情報)

to reviewer: 不明点などお願いします

`zod` (https://zod.dev) という validate-er を使って記述しているので, この PR を閉じる前に依存を追加する Issue を立てておく

- [ ] Issue を建てる: #

2023-05-16 05:01 UTC, raiga0310 requested changes

2023-05-16 05:01 UTC, raiga0310 commented on docs/ARCHITECTURE.md
> +`global.settings` と比較するとこれは遊び心地やプラットフォーム毎の調整なのに対し, これはゲームのシステム或いは核心に対する調整であることが違う.
```suggestion
`global.settings` は遊び心地やプラットフォーム毎の調整なのに対し, これはゲームのシステム或いは核心に対する調整であることが違う.
```

｢これ｣を複数に同時で使うのは伝わりづらいかな､と

2023-05-16 05:01 UTC, raiga0310 commented on docs/schema.ts
> +  // 概ね有名か, 最も使われている順とする
おそらく今PRでは関係ないですが･････ここの基準について概ね有名､は具体的な基準化必要になるんじゃないかなぁ､と

2023-05-17 07:12 UTC, Nanai10a commented on docs/schema.ts
> +  // 概ね有名か, 最も使われている順とする
ぶっちゃけ言語に依ると思うので, あんま強く書かなかっただけですが… "公式がそうしている" としても良い気はしますけどね (使われているかに関わらず)

2023-05-17 08:27 UTC, raiga0310 commented on docs/schema.ts
> +  // 概ね有名か, 最も使われている順とする
OK

2023-05-17 08:27 UTC, raiga0310 approved these changes
LGTM

2023-05-18 01:42 UTC, merged